### ISSUE TITLE
Chars2vec for text classification 

### ISSUE THREAD

**Issue by Rahulvks** [IntuitionEngineeringTeam/chars2vec#2]
Hi 

Thanks for this Wonderfull library.

Is any examples are available to use Chars2vec in text classification ?

**Comment by v4ikin** [comment]
Hi,

You can find a small example of text classification using chars2vec in the article about chars2vec in the Benchmarks section:

https://hackernoon.com/chars2vec-character-based-language-model-for-handling-real-world-texts-with-spelling-errors-and-a3e4053a147d
