### ISSUE TITLE
chars2vec.load_model('eng_50')- got an unexpected keyword argument 'maximum_iterations'

### ISSUE THREAD

**Issue by Rahulvks** [IntuitionEngineeringTeam/chars2vec#3]
```
import keras
import chars2vec
c2v_model = chars2vec.load_model('eng_50')
```

Am facing below error while load model

`/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in rnn(step_function, inputs, initial_states, go_backwards, mask, constants, unroll, input_length)
   3009             parallel_iterations=32,
   3010             swap_memory=True,
-> 3011             maximum_iterations=input_length)
   3012         last_time = final_outputs[0]
   3013         output_ta = final_outputs[1]

TypeError: while_loop() got an unexpected keyword argument 'maximum_iterations'

`

**Comment by v4ikin** [comment]
Please update your Tensorflow and Keras libraries and try again.
